# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Q2mazd601TFpL_Rm-1GVrUEbsHFrubp
"""

import streamlit as st
import joblib
import pandas as pd

# ==============================
# Page Configuration
# ==============================

st.set_page_config(
    page_title="Malaysia Housing Price Predictor",
    page_icon="🏠",
    layout="centered"
)

# ==============================
# Load Dataset
# ==============================

@st.cache_data
def load_data():
    return pd.read_csv("malaysia_house_price_data_2025.csv")

df = load_data()

# Get unique categorical values from the dataset
areas = sorted(
    df["Area"].dropna().unique().tolist()
)

states = sorted(
    df["State"].dropna().unique().tolist()
)

tenures = sorted(
    df["Tenure"].dropna().unique().tolist()
)

property_types = sorted(
    df["Type"].dropna().unique().tolist()
)

# ==============================
# Load Trained Model
# ==============================

@st.cache_resource
def load_model():
    model_bundle = joblib.load("housing_price_catboost.joblib")
    return model_bundle

model_bundle = load_model()

model = model_bundle["model"]

# ==============================
# Main Page
# ==============================

st.title("🏠 Malaysia Housing Price Predictor")

st.write(
    "This application predicts the median property price "
    "of residential properties in Malaysia."
)

st.write(
    "Enter the property information below to get an estimated "
    "median property price."
)

# ==============================
# Model Information
# ==============================

st.info(
    "Machine Learning Model: CatBoost Regressor"
)

st.divider()

# ==============================
# Property Information
# ==============================

st.header("🏡 Property Information")

st.write(
    "Please provide the following property details:"
)

# Area
area = st.selectbox(
    "Area",
    areas
)

#State
state = st.selectbox(
    "State",
    states
)

# Tenure
tenure = st.selectbox(
    "Tenure",
    tenures
)

# Property Type
property_type = st.selectbox(
    "Property Type",
    property_types
)

# Median PSF
median_psf = st.number_input(
    "Median Price Per Square Foot (RM)",
    min_value=0.0,
    value=300.0,
    step=1.0
)

# Transactions
transactions = st.number_input(
    "Number of Transactions",
    min_value=0,
    value=100,
    step=1
)

# ==============================
# Prediction
# ==============================

st.divider()

st.header("💰 Price Prediction")

if st.button("Predict Median Price"):

    # Create input data for the model
    input_data = pd.DataFrame({
        "Area": [area],
        "State": [state],
        "Tenure": [tenure],
        "Type": [property_type],
        "Median_PSF": [median_psf],
        "Transactions": [transactions]
    })

    # Make prediction
    prediction = model.predict(input_data)[0]

    # Display prediction
    st.success(
        f"Estimated Median Property Price: RM {prediction:,.2f}"
    )